---
type: docker
kind: pipeline
name: default

steps:
- name: submodules
  image: alpine/git
  commands:
  - git submodule update --init --recursive
- name: Run
  image: docker:dind
  volumes:
  - name: dockersock
    path: /var/run
  commands:
  - apk update
  - apk add docker-compose
  - docker-compose -p chipollino up -d --build
  when:
    branch:
    - main
    event:
    - push


volumes:
- name: dockersock
  host:
    path: /var/run