---
steps:
  - name: build-and-run
    image: nixos/nix
    entrypoint:
      - /run/current-system/sw/bin/bash
      - -c
      - echo $CI_SCRIPT | base64 -d | /run/current-system/sw/bin/bash -e
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /nix/var/nix/daemon-socket/socket:/nix/var/nix/daemon-socket/socket
      - /nix/store:/nix/store:ro
      - /run/current-system/sw/bin:/run/current-system/sw/bin:ro
      - /nix/var/nix/profiles/per-user/root/channels/nixos:/nixpkgs:ro
    environment:
      NIX_REMOTE: daemon
      PATH: /run/current-system/sw/bin:/usr/bin:/bin
      NIX_PATH: nixpkgs=/nixpkgs
    commands:
      - nix-shell -p docker --run "
          nix-build docker.nix --max-jobs 1 --cores 1
          && docker load < result/app
          && docker load < result/caddy
          && docker compose -p chipollino_web up -d
        "
    when:
      branch:
        - main
      event:
        - push
