---
steps:
  - name: build-and-run
    image: ghcr.io/cachix/devenv/devenv:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /nix/var/nix/daemon-socket/socket:/nix/var/nix/daemon-socket/socket
      - /nix/store:/nix/store:ro
      - /run/current-system/sw/bin:/run/current-system/sw/bin:ro
      - /nix/var/nix/profiles/per-user/root/channels/nixos:/nixpkgs:ro
    environment:
      NIX_REMOTE: daemon
      PATH: /run/current-system/sw/bin:/usr/bin:/bin
      NIX_PATH: nixpkgs=/nixpkgs
    commands:
      - devenv container build app
      - devenv container copy app
      - devenv container build caddy
      - devenv container copy caddy
      - nix-shell -p docker --run "docker compose -p chipollino_web up -d"
    when:
      branch:
        - main
      event:
        - push
