services:
  app:
    build: .
    volumes:
      - db:/db
    restart: unless-stopped
    environment:
      - DJANGO_DEBUG=0
      - DJANGO_DB=/db/db.sqlite3
      - CHIPOLLINO_BINARY=build/apps/InterpreterApp/InterpreterApp
      - CHIPOLLINO_GENERATOR_BINARY=build/apps/InputGeneratorApp/InputGeneratorApp
  caddy:
    build: 
      context: .
      dockerfile: ./caddy/Dockerfile
    restart: unless-stopped
    ports:
      - 127.0.0.1:8000:8000
volumes:
  db:
