# Generated by Django 5.0.6 on 2024-06-15 04:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GraphDB",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodes", models.JSONField(default=list)),
                ("edges", models.JSONField(default=list)),
                ("session_key", models.CharField(max_length=40, null=True)),
                ("name", models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="TemporaryFile",
            fields=[
                ("path", models.TextField(primary_key=True, serialize=False)),
                ("session_key", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
