# Generated by Django 5.0.6 on 2024-06-02 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemporaryFile",
            fields=[
                ("path", models.TextField(primary_key=True, serialize=False)),
                ("session_key", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Graph",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodes", models.JSONField(default=list)),
                ("edges", models.JSONField(default=list)),
                ("session_key", models.CharField(max_length=40)),
                ("name", models.CharField(max_length=255, null=True)),
                (
                    "temporary_file",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="converter.temporaryfile",
                    ),
                ),
            ],
        ),
    ]
