# Generated by Django 5.0.6 on 2024-06-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("converter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphdb",
            name="type",
            field=models.CharField(
                choices=[("NFA", "NFA"), ("MFA", "MFA")], default="NFA", max_length=50
            ),
        ),
    ]
