# Generated by Django 5.0.6 on 2024-06-02 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemporaryFile',
            fields=[
                ('path', models.TextField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
