# Generated by Django 5.0.6 on 2024-07-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("converter", "0002_graphdb_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="graphdb",
            name="username",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
