chipollino_path: ../Chipollino

types:
  NFA:
    class: FiniteAutomaton
    children: [DFA, RandomNFA]
    ru_str: автомат
  DFA:
    class: FiniteAutomaton
    children: [RandomDFA]
    ru_str: автомат
  MFA:
    class: MemoryFiniteAutomaton
    children: [NFA, RandomMFA]
    ru_str: автомат
  Regex:
    class: Regex
    children: [RandomRegex]
    ru_str: регулярное выражение
  BRefRegex:
    class: BackRefRegex
    children: [Regex, RandomBRefRegex]
    ru_str: регулярное выражение
  RandomRegex:
  RandomBRefRegex:
  RandomDFA:
  RandomNFA:
  RandomMFA:
  Int:
    class: int
    ru_str: значение
  FileName:
    class: std::string
    ru_str: строка
  Boolean:
    class: bool
    ru_str: значение
  OptionalBool:
    class: std::optional<bool>
    ru_str: значение
  AmbiguityValue:
    class: FiniteAutomaton::AmbiguityValue
    ru_str: значение
  PrefixGrammar:
    class: PrefixGrammar
    ru_str: грамматика
  Array:
    class: std::vector<GeneralObject>
    ru_str: массив

classes: 
  FiniteAutomaton: 
    file: FiniteAutomaton
    extends: AbstractMachine
  MemoryFiniteAutomaton: 
    file: MemoryFiniteAutomaton
    extends: AbstractMachine
  Regex: 
    file: Regex
    extends: AlgExpression
  BackRefRegex: 
    file: BackRefRegex
    extends: AlgExpression
  PrefixGrammar: 
    file: Grammar

functions:
 - name: Thompson
   prog_name: to_thompson
   return_type: NFA
   arguments: [Regex]

 - name: IlieYu
   prog_name: 
   return_type: NFA
   arguments: [Regex]

 - name: Antimirov
   prog_name: 
   return_type: NFA
   arguments: [Regex]

 - name: Arden
   prog_name: 
   return_type: Regex
   arguments: [NFA]

 - name: Glushkov
   prog_name: 
   return_type: NFA
   arguments: [Regex]

 - name: MFA
   prog_name: to_mfa
   return_type: MFA
   arguments: [BRefRegex]

 - name: MFAexpt
   prog_name: to_mfa_additional
   return_type: MFA
   arguments: [ BRefRegex ]

 - name: Determinize
   prog_name: 
   return_type: DFA
   arguments: [NFA]

 - name: Determinize+
   prog_name: 
   return_type: DFA
   arguments: [NFA]
   need_template: false 

 - name: RemEps
   prog_name: 
   return_type: NFA
   arguments: [NFA]

 - name: RemEps
   prog_name:
   return_type: MFA
   arguments: [ MFA ]

 - name: Linearize
   prog_name: 
   return_type: Regex
   arguments: [Regex]

 - name: Minimize
   prog_name: 
   return_type: DFA
   arguments: [NFA]

 - name: Minimize+
   prog_name: 
   return_type: DFA
   arguments: [NFA]
   need_template: false 

 - name: Reverse
   prog_name: reverse
   return_type: NFA
   arguments: [NFA]

 - name: Reverse
   prog_name: reverse
   return_type: BRefRegex
   arguments: [BRefRegex]

 - name: Annote
   prog_name: 
   return_type: DFA
   arguments: [NFA]

 - name: DeLinearize
   prog_name: 
   return_type: Regex
   arguments: [Regex]

 - name: DeLinearize
   prog_name: 
   return_type: NFA
   arguments: [NFA]

 - name: AddTrap
   prog_name: add_trap_state
   return_type: MFA
   arguments: [ MFA ]

 - name: Complement
   prog_name: 
   return_type: DFA
   arguments: [DFA]

 - name: Complement
   prog_name: complement
   return_type: MFA
   arguments: [ MFA ]

 - name: RemoveTrap
   prog_name: 
   return_type: DFA
   arguments: [DFA]

 - name: DeAnnote
   prog_name: 
   return_type: Regex
   arguments: [Regex]

 - name: DeAnnote
   prog_name: 
   return_type: NFA
   arguments: [NFA]

 - name: MergeBisim
   prog_name: 
   return_type: NFA
   arguments: [NFA]

 - name: Disambiguate
   prog_name: 
   return_type: Regex
   arguments: [Regex]

 - name: Intersect
   prog_name: 
   return_type: NFA
   arguments: [NFA, NFA]

 - name: Union
   prog_name: 
   return_type: NFA
   arguments: [NFA, NFA]

 - name: Difference
   prog_name: 
   return_type: NFA
   arguments: [NFA, NFA]

 - name: PumpLength
   prog_name: 
   return_type: Int
   arguments: [Regex]

 - name: ClassLength
   prog_name: 
   return_type: Int
   arguments: [NFA]

 - name: Normalize
   prog_name: 
   return_type: Regex
   arguments: [Regex, Array]

 - name: States
   prog_name: 
   return_type: Int
   arguments: [NFA]

 - name: ClassCard
   prog_name: 
   return_type: Int
   arguments: [NFA]

 - name: Ambiguity
   prog_name: 
   return_type: AmbiguityValue
   arguments: [NFA]

 - name: MyhillNerode
   prog_name: 
   return_type: Int
   arguments: [NFA]

 - name: GlaisterShallit
   prog_name: 
   return_type: Int
   arguments: [NFA]

 - name: PrefixGrammar
   prog_name: 
   return_type: PrefixGrammar
   arguments: [NFA]

 - name: PGtoNFA
   prog_name: 
   return_type: NFA
   arguments: [PrefixGrammar]

 - name: Bisimilar
   prog_name: bisimilar
   return_type: Boolean
   arguments: [NFA, NFA]

 - name: Minimal
   prog_name: 
   return_type: OptionalBool
   arguments: [NFA]

 - name: Deterministic
   prog_name: 
   return_type: Boolean
   arguments: [NFA]

 - name: Deterministic
   prog_name: is_deterministic
   return_type: Boolean
   arguments: [ MFA ]

 - name: Subset
   prog_name: subset
   return_type: Boolean
   arguments: [Regex, Regex]

 - name: Subset
   prog_name: subset
   return_type: Boolean
   arguments: [NFA, NFA]

 - name: Equiv
   prog_name: 
   return_type: Boolean
   arguments: [Regex, Regex]

 - name: Equiv
   prog_name: 
   return_type: Boolean
   arguments: [NFA, NFA]

 - name: Equal
   prog_name: 
   return_type: Boolean
   arguments: [Regex, Regex]

 - name: Equal
   prog_name: 
   return_type: Boolean
   arguments: [NFA, NFA]

 - name: Equal
   prog_name: 
   return_type: Boolean
   arguments: [Int, Int]

 - name: Equal
   prog_name: 
   return_type: Boolean
   arguments: [AmbiguityValue, AmbiguityValue]

 - name: Equal
   prog_name: 
   return_type: Boolean
   arguments: [Boolean, Boolean]

 - name: OneUnambiguity
   prog_name: 
   return_type: Boolean
   arguments: [Regex]

 - name: OneUnambiguity
   prog_name: 
   return_type: Boolean
   arguments: [NFA]

 - name: SemDet
   prog_name: 
   return_type: Boolean
   arguments: [NFA]

 - name: IsAcreg
   prog_name: is_acreg
   return_type: Boolean
   arguments: [BRefRegex]

#  - name: Bisimilar
#    prog_name: bisimilar
#    return_type: OptionalBool
#    arguments: [MFA, MFA]

#  - name: ActionBisimilar
#    prog_name: action_bisimilar
#    return_type: Boolean
#    arguments: [MFA, MFA]

#  - name: LiterallyBisimilar
#    prog_name: literally_bisimilar
#    return_type: Boolean
#    arguments: [MFA, MFA]

 - name: getNFA
   prog_name: 
   return_type: NFA
   arguments: [FileName]
   need_template: false 

 - name: getMFA
   prog_name: 
   return_type: MFA
   arguments: [FileName]
   need_template: false 
  
 - name: getDFA
   prog_name: 
   return_type: DFA
   arguments: [FileName]
   need_template: false 